from tkinter import *

root = Tk()

canvas = Canvas(root, width='400', height='600')
canvas.pack()
# 21 db egy oldalon ~25oldalszélesség
# reproduce this:
# [https://github.com/greenfox-academy/teaching-materials/blob/master/workshop/drawing/triangles/r5.png]
def draw_triangles(x, y):
    black_line = canvas.create_line(x, y, x + 7.5, y + 15, fill="black")
    black_line = canvas.create_line(x, y, x - 7.5, y + 15, fill="black")
    black_line = canvas.create_line(x - 7.5, y + 15, x + 7.5, y + 15, fill="black")

x = 200
y = 100

for i in range(22):
    y += 15
    x -= 7.5
    for j in range(i):
        x += 15
        draw_triangles(x, y)
    x -= i * 15

root.mainloop()
#----------------------------------------
from tkinter import *
from math import sqrt

root = Tk()

canvas = Canvas(root, width='600', height='600')
canvas.pack()

rows = int(input("number of rows generated by triangels: "))

a = 600 // rows
h = int(a*sqrt(3)/2)

def tri(x,y, a, h):
    tri = canvas.create_polygon(x, y, x + a, y, x + a/2, y - h, outline='black', fill='white', width=1)

for i in range(rows):
    for j in range(rows-i):
        tri(j*a+i*a/2, 600-(i*h), a, h)

root.mainloop()